name: test release to fix finalize release

trigger:
  branches:
    include:
      - mikeN/*

pool:
  vmImage: ubuntu-latest

jobs:
  - job: Fake_Release
    displayName: Add small change to Changelog
    steps:
      - checkout: self
        persistCredentials: true
        fetchDepth: 0
      - bash: git status
        displayName: check branch
      - task: NodeTool@0
        displayName: Use Node 20.x
        inputs:
          versionSpec: 20.x
          checkLatest: true
      - script: |
          echo "The current branch is $(Build.SourceBranch)"
        displayName: 'Print current branch'
      - bash: |
          git config --local user.email 38288322+imodeljs-admin@users.noreply.github.com
          git config --local user.name imodeljs-admin
        displayName: Setup Git

      - bash: |
          echo "test change" >> 'core/backend/CHANGELOG.md'
          cat 'core/backend/CHANGELOG.md'

      - bash: "git add ."
        displayName: Git add

      - bash: |
          echo Committing version bump 4.6.11...
          git commit -m "4.6.11" --author="imodeljs-admin <38288322+imodeljs-admin@users.noreply.github.com>"
        displayName: Git commit dummy version # TODO: try 4.6.11 as patch and 4.6.0 as minor

      # - ? ${{ if or(eq(parameters.BumpType, 'minor'), eq(parameters.BumpType, 'patch')) }}
      #   : - bash: 'git tag -a release/$(getVersion.version) -m "v$(getVersion.version)"'
      #       displayName: Create git tag

      - bash: "git push https://$(GITHUBTOKEN)@github.com/iTwin/itwinjs-core HEAD:$(Build.SourceBranch)"
        displayName: Push version bump